### ISSUE TITLE
1.0.5 not working on IOS

### ISSUE THREAD

**Issue by gdigesu** [thingnotok/obsidian-toggle-list#10]
Hi,

Since the update from 1.0.4 to 1.0.5, you can't add ToggleList to the mobile bar.

Can you help?

**Comment by thingnotok** [comment]
Hi I just tried and it works on my phone.  The command name is changed and is configurable in 1.0.5. You may need to add the command from Mobile/More toolbar options again (and every time you change the command name). 

If it doesn't fix your problem, can you present more detail on the bug?

![IMG_6AC88F5FDD22-1](https://user-images.githubusercontent.com/29173832/201338791-83514733-7788-4892-8996-709bbfac1cc4.jpeg)
![IMG_D8195C2B11E2-1](https://user-images.githubusercontent.com/29173832/201338800-4c6e011e-b670-4bb4-b16e-685351cb653d.jpeg)

**Comment by gdigesu** [comment]
Hi

On my end, I now have 1.0.6 and it is working.
Thanks form the prompt reply!

On 11 Nov 2022, at 9:21 AM, thingnotok ***@***.***> wrote:



Hi I just tried and it works on my phone. The command name is changed and is configurable in 1.0.5. You may need to add the command from Mobile/More toolbar options again (and every time you change the command name).

If it doesn't fix your problem, can you present more detail on the bug?

[IMG_6AC88F5FDD22-1]<https://bra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F29173832%2F201338791-83514733-7788-4892-8996-709bbfac1cc4.jpeg&data=05%7C01%7Cg%40digesu.com.br%7C9e5c355dadda40a0356308dac3df495a%7C718f3212162b4bf891c55c06573e715e%7C0%7C0%7C638037661070623134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nA1n3ae6JRY48QUTxa%2Fi3uVFAE71VEpPMAJzgOCObVU%3D&reserved=0>
[IMG_D8195C2B11E2-1]<https://bra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F29173832%2F201338800-4c6e011e-b670-4bb4-b16e-685351cb653d.jpeg&data=05%7C01%7Cg%40digesu.com.br%7C9e5c355dadda40a0356308dac3df495a%7C718f3212162b4bf891c55c06573e715e%7C0%7C0%7C638037661070623134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ESWCUiPm2gdMP3xePDHL9ybzjMsjC%2FAOyIZUagqy7GM%3D&reserved=0>

**Comment by thingnotok** [comment]
Haha, then I have no idea why it works. The 1.0.6 version is for another issue. But I'm glad it works on your device now. 
I'll close this issue. Feel free to open a new issue if anything bad occurs.
