### ISSUE TITLE
possible bug only first state group (tasks) works?

### ISSUE THREAD

**Issue by erauner12** [thingnotok/obsidian-toggle-list#11]
not sure if this impacting anyone else but only the first state group works for me?

https://www.loom.com/share/21dc3b1262404b47ab5ba18a0c0a653e

**Comment by thingnotok** [comment]
Hi @erauner12, is your problem solved?

**Comment by erauner12** [comment]
Yeah, sorry I was using the tool incorrectly 😅 I appreciate the follow up 🙂
