### ISSUE TITLE
Feature request: second set of checkboxes 

### ISSUE THREAD

**Issue by TaardeT** [thingnotok/obsidian-toggle-list#2]
Hi! If it is possible, it would be great to have second set of checkboxes to use it with another hotkey (for example I use done/incomplete/forwarded for my to-do and question/important/idea for my study notes, it would be cool to run through them separately)

Thanks for the great plugin! (:

**Comment by thingnotok** [comment]
Thanks! Love your idea. I’ll try to implement it this week.

**Comment by thingnotok** [comment]
Hi! Thanks for your suggestion again! I've implement the request feature. You can download it from [the release page](https://github.com/thingnotok/obsidian-toggle-list/releases/tag/1.0.1), or install with [BRAT plugin](https://github.com/TfTHacker/obsidian42-brat).

Please let me know if there's any bugs : )
