### ISSUE TITLE
Feature Request: add option to diable suggestion box when there are only two states in a state group.

### ISSUE THREAD

**Issue by YousufSSyed** [thingnotok/obsidian-toggle-list#21]
When I have two states in a state group and I activate the command to cycle between it, it shows the suggestion box below the task text. If a task item is in one state, it should just switch to the other. This can be opt in by adding a setting.

**Comment by thingnotok** [comment]
Hello! You can turn off the suggestion box by toggling this option, regardless of how many states are in that group.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/29173832/222863262-e22060cf-4348-47f8-a426-54a34a397304.png">

**Comment by YousufSSyed** [comment]
I did that and it worked, though I should note that the  `ToggleList Task-POP`(when my command is called "Task") got removed and got replaced with `ToggleList: Task-Prev` and `ToggleList: Task-Next`.

@thingnotok shouldn't u add this to the readme?

**Comment by thingnotok** [comment]
@YousufSSyed  Sorry for the inconvenience. The latest release has merged the pop action with the Next/Prev actions, eliminating confusing action naming handling in future.

**Comment by YousufSSyed** [comment]
Alright look good, thanks!
