### ISSUE TITLE
{tasks-today} shows tomorrow instead of today

### ISSUE THREAD

**Issue by uwidev** [thingnotok/obsidian-toggle-list#23]
Not too sure why, but instead of today, it shows tomorrow. Might be a timezone problem? Though I can't see why this plugin would use anything other than my local computer time. How can I go about troubleshooting this?

**Comment by thingnotok** [comment]
Apologies for the delayed response. I believe I have identified the bug. Could you please provide me with your timezone and the exact time when the bug occurs? This information will help me confirm the issue. Thank you for bringing this to my attention.

**Comment by thingnotok** [comment]
Release 1.2.1 has addressed this bug. The previous implementation resulted in incorrect dates due to a missing timezone offset. Please let me know if this resolves your issue.
