### ISSUE TITLE
Support {task-created-today}

### ISSUE THREAD

**Issue by erauner12** [thingnotok/obsidian-toggle-list#25]
The tasks plugin uses: `✅` to signify when a task is completed. But I'm wondering if you can add an additional template for the tasks that are created today: `➕`

ex: 
```
- [ ] test ➕ 2023-09-01
```

Let me know if you have any questions!

**Comment by petitpandarouge** [comment]
Why not go for adding just {date}? Or maybe {today} to reflect the plugin conventions.
The idea is that I'm using it but with the Dataview plugin naming.
For example, for the completion, I would like [completion:: {today}].
By adding this, I think it'll be easier for everyone to play with it.
What do you think about it?

**Comment by erauner12** [comment]
Yeah I like it!

**Comment by thingnotok** [comment]
@erauner12 @petitpandarouge, thank you for your valuable suggestions. In Release 1.2.1, I've incorporated support for the new time format. You can now use `{time:: YYYY-MM-DD}` to add time. Please note that the ✅ has been removed. To set the state, you should use `- [ ] || ➕ {time:: YYYY-MM-DD}`.

Please let me know if anything is not working.
