### ISSUE TITLE
Keep preferences from being reset to default when the plugin is updated

### ISSUE THREAD

**Issue by eXperitur** [thingnotok/obsidian-toggle-list#27]
Hi! Thanks for this great plugin! 

My only issue with it is that I seem to be losing my preferences in the user input boxes for state groups each time there's an update. Is this something that can be fixed? Or maybe I'm be doing something wrong?

**Comment by thingnotok** [comment]
Thank you for your feedback and for using the plugin! I apologize for the inconvenience you've experienced with losing your preferences after updates. This issue occurs when the new preference is not compatible with the previous preference json file. Rest assured, I am aware of this problem and will be testing preference backward compatibility in future releases.
