### ISSUE TITLE
Toggle task status will broken the reference id

### ISSUE THREAD

**Issue by quanru** [thingnotok/obsidian-toggle-list#29]
![image](https://github.com/thingnotok/obsidian-toggle-list/assets/11739753/9ca6f442-e99a-4861-bac3-fe985653d3db)

Normally it should be like this:
![image](https://github.com/thingnotok/obsidian-toggle-list/assets/11739753/63538d05-1268-4514-a944-9f0f66b92296)

But with toggle list plugin:
![image](https://github.com/thingnotok/obsidian-toggle-list/assets/11739753/64346767-b2ba-422b-aa31-8a898f72755a)

**Comment by thingnotok** [comment]
Yes, the current version will cause this issue. I will add this feature in the next version.

**Comment by thingnotok** [comment]
Hey, version 1.2.3 now includes this feature. Please let me if it functions properly for you.

**Comment by quanru** [comment]
> Hey, version 1.2.3 now includes this feature. Please let me if it functions properly for you.

It's working perfectly now, thank you~~
