### ISSUE TITLE
Why this plugin has 184487 lines of code?

### ISSUE THREAD

**Issue by juanbretti** [thingnotok/obsidian-toggle-list#33]
For some reason, this plugin while running on Obsidian, has 184487 lines of code.
Does anyone happen to know why?

![image](https://github.com/thingnotok/obsidian-toggle-list/assets/10165911/74286ea9-7953-4086-879b-ae063cd9f877)

This is a 6.74 MiB file:

![image](https://github.com/thingnotok/obsidian-toggle-list/assets/10165911/8ef5835f-de08-4139-9f61-e0108a83996d)

**Comment by Slider2k** [comment]
Yeah, it's quite ridiculous.
And the code is a whole bunch of incoherent nonsense.

> THIS IS A GENERATED/BUNDLED FILE BY ESBUILD

This should give a hint, that the code is auto-generated. We see the result of TypeScript being compiled terribly to JavaScript.

**Comment by Slider2k** [comment]
Well, this has gone strange. When I tried to uninstall the plugin the Obsidian could not finish it. I checked the plugin folder, and the folder contained only main.js left. When I deleted the file manually, it instantly reappeared. I checked what process had the main.js find handle opened, the Process Explorer said it was System. I logged out from my account and logged it again. The main.js was still there and refused to be deleted still. Then I renamed the plugin folder and the main.js disappeared. Seems kind of sus.

**Comment by juanbretti** [comment]
I am not sure, but I think the size of the plugin has to do with a mistaken library import.
In particular, importing the library that plots the colored graph that shows at the bottom.

![image](https://github.com/thingnotok/obsidian-toggle-list/assets/10165911/9bd96717-020c-48fe-88fc-cad157a92d3f)

I tried installing and uninstalling the plugin, and I had no issues.
It is sad the developer went AWOL, it is a very nice plugin that just need a few touches to be perfect. Like fixing issue #31 .

Alternativelly, you could try **Task Collector**: https://forum.obsidian.md/t/is-there-any-way-to-cycle-through-more-bullet-markers/75830/4?u=juanbretti

**Comment by Slider2k** [comment]
Looking through my plugins folder I've found another plugin with the same affliction: "Tag Overview"

Same bloated, generated code by ESBUILD.

I don't know, maybe the devs aren't using the build tool properly or what.

**Comment by hmijail** [comment]
I have no idea about the build process nor how big should the plugin be, but to be fair, the graph is a very nice way to visualize the interaction of state groups and how they get bound by commands.

I tried Task Collector. It deals with the checkboxes, but not with the date toggling. So I'm back to ToggleList.

**Comment by thingnotok** [comment]
@juanbretti You're right, the package used to draw the state diagram accounts for 99% of the space. I'm considering using Obsidian's JSON Canvas format in the next version, which should completely resolve this issue. For now, I will include a version without the state diagram in the release, allowing those who care to replace it.

Method: Download `main-slim.js` and replace the `main.js` file in `vault path/.obsidian/plugins/obsidian-toggle-list`.

**Comment by thingnotok** [comment]
resovled in 423e0843e3abb7ecc633af9da207d5f2f2dbc79d
is included in the latest release
