### ISSUE TITLE
Supporting for Android

### ISSUE THREAD

**Issue by TaardeT** [thingnotok/obsidian-toggle-list#4]
Hi! After last update plugin doesn't work on Android, neither with community plugins nor with BRAT installing

**Comment by thingnotok** [comment]
Hi I didn’t expect the plugin would be used on mobile devices, so I turned the only for desktop on in the manifest.json. I don’t have an android device, can you help describe the situation in details or try set the flag in manifest.json?

Thanks😃

Here's the only thing I touched related to mobile devices, you can try modify the last line to false.  Or I can also borrow an andirod from my friend to test, but it may take several days.
```json
{
	"id": "obsidian-toggle-list",
	"name": "ToggleList",
	"version": "1.0.2",
	"minAppVersion": "0.15.0",
	"description": "Toggle the checklist with custom states",
	"author": "Lite C",
	"authorUrl": "https://github.com/thingnotok/obsidian-simple-todo",
	"isDesktopOnly": true
}
```

**Comment by TaardeT** [comment]
Hi! Thanks, did it, it is working now)

**Comment by thingnotok** [comment]
No problem! I update the manifest file in the release, so you can install the correct version from community plugin. But the only difference is: `"isDesktopOnly": false`, so you don't have to do that.
