### ISSUE TITLE
1.0.1 Not working on IOS

### ISSUE THREAD

**Issue by gdigesu** [thingnotok/obsidian-toggle-list#5]
1.0 did work on IOS.
Can you help?

**Comment by thingnotok** [comment]
Hi, a setting was wrong in last release. You can delete and reinstall the plugin to fix it. Please let me know if if works!

**Comment by gdigesu** [comment]
Hi,

I'm afraid it is not working.
See pic attached of a few minutes ago.

[image0.png]

On 25 Oct 2022, at 9:54 PM, thingnotok ***@***.***> wrote:

﻿

Hi, a setting was wrong in last release. You can delete and reinstall the plugin to fix it. Please let me know if if works!

**Comment by gdigesu** [comment]
The pic ...

Similar behavior on iPad.

![ABC4B651-CFA1-4B7B-90DE-DADE50F2CABF](https://user-images.githubusercontent.com/44509843/197982157-79a63973-2fda-40f2-a43d-95e77cf12377.png)

**Comment by thingnotok** [comment]
Hi, sorry I misunderstood how obsidian pull plugins so the changes were not working.  
I just update the setting and can download the plugin from community plugin with my iphone (ios 16.0). Keep me updated if it it works. You may need to restart the app or something to let the app fetch the new files.

btw, just curious, I'm not using obsidian on mobile devices, but as this plugin is only useful with keyboard hotkeys, how do you guys use it on a phone? 

![IMG_4354D2324295-1](https://user-images.githubusercontent.com/29173832/198007790-f054e3cd-b3a9-4878-8f1c-6a9f4bb214c5.jpeg)

**Comment by gdigesu** [comment]
Thanks! It works.

To make it work on IOS, go to Options > Mobile, and add ToggleList two options to the mobile bar. 😎
