### ISSUE TITLE
[Feature Request] context-based state cycling

### ISSUE THREAD

**Issue by clydebaron2000** [thingnotok/obsidian-toggle-list#8]
I am currently tying to bind two different cycles to the same command, one for callout bullets and one for custom task bullets.
i believe that you should have the option to cycle through any of the states you have with one command ie:

if you have two state cycles:
State 0
```
- [ ] ||
- [?] ||
```
State 1
```
||
- ||
- i
```
i should be able to do:

` ` (ctrl+enter) (state1)
`- ||` (ctrl+enter) (state1)
`- i` (ctrl+enter) (state1)
`- [ ] i` (typed)
`- [?] i` (ctrl+enter) (state0)

**Comment by thingnotok** [comment]
Thanks to your proposal. So you're saying that you want to assign two(or more) attributes to a list right? In your example, a call out tag and a task tag. And you want to use a single hotkey for that. Which means that next state is still only rely on the current state. In my design, it will only take one state group to achieve this. 

If I'm not getting it wrong, how about using the following state group? It still use two hotkeys (prev and next), but you can still go through all state with only next command. Or you can manually edit the line to jump to certain state.

``` md
- [?] 
- [ ]

- 
- i 
- [ ] i 
- [?] i 
```

It's possible to generate the compound group with two group as you suggest, but I can't find an easy way to determine how to links all the combinations at the first glance. It would be great if you can elaborate on this more.

Another related feature I'm thinking about is to have multiple independent prefixes, and each is triggered with different hotkey. So tags and list states can toggles independently. I believe this can be useful to organizing tasks.

**Comment by clydebaron2000** [comment]
What I am saying is, I believe that states should be able to be triggered with the *same* hotkey. Notice in my example that with *one* hotkey i was able to go to the next state by just typing a different prefix manually.

Of course with this, there arises a problem of state cycle collisions (two states having the same prefix somewhere) but you could resolve that by taking the first state cycle as priority.

**Comment by thingnotok** [comment]
Ok I get it. This should be easy. I'll try to add this in the next release! Thanks for clarifying!

in processOneLine (LINE):
for sg in state_groups: // priority order
      if LINE match state in sg:
             toggle LINE to next state in sg.
             break

**Comment by thingnotok** [comment]
@clydebaron2000  I tried to implement this yesterday. Here's the progress

Now you can specify which groups to bind with each command. The order of groups in the binding list is their priority in state mating process. I want to make sure that the video matches what you suggest. 

https://user-images.githubusercontent.com/29173832/200152440-80cabef5-98fb-4a51-a319-090353dfafd0.mov

The UI is basic, and using index number to identify groups and commands are really confusing now. I'll add naming support to both groups and commands later. 

Here's the pre-released js file. You can try out first! https://drive.google.com/file/d/11wANOVHpdxUHIjIR-rgjMEk4oGxIR3qv/view?usp=sharing

**Comment by thingnotok** [comment]
The feature is add in the latest release.
